---
app_name: devops-app-py
docker_image: "{{ dockerhub_username }}/{{ app_name }}"
docker_image_tag: latest

app_port: 5000
app_container_name: devops-app
app_container_internal_port: 5000
app_restart_policy: unless-stopped

app_environment:
  HOST: "0.0.0.0"
  PORT: "{{ app_container_internal_port | string }}"
app_container_command: "gunicorn --bind 0.0.0.0:{{ app_container_internal_port }} src.main:app"

app_healthcheck_path: /health
app_healthcheck_retries: 20
app_healthcheck_delay: 3
app_healthcheck_timeout: 3
app_recreate_on_pull: true
app_healthcheck_host: "{{ ansible_host | default(inventory_hostname) }}"
app_healthcheck_delegate_to: localhost
