name: Python Poetry Setup
description: Set up Python + Poetry, cache dependencies, and install project deps

inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.14"
  poetry-version:
    description: Poetry version to install
    required: false
    default: "2.3.2"
  working-directory:
    description: Project directory containing pyproject.toml
    required: false
    default: "app_python"
  lockfile-path:
    description: Path to poetry.lock for cache key invalidation
    required: false
    default: "app_python/poetry.lock"
  install-args:
    description: Extra arguments passed to poetry install
    required: false
    default: "--with dev --no-interaction --no-ansi"

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry-version }}

    - name: Configure Poetry virtualenv location
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: poetry config virtualenvs.in-project true

    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          ${{ inputs.working-directory }}/.venv
        key: ${{ runner.os }}-py${{ inputs.python-version }}-poetry${{ inputs.poetry-version }}-${{ hashFiles(inputs.lockfile-path) }}
        restore-keys: |
          ${{ runner.os }}-py${{ inputs.python-version }}-poetry${{ inputs.poetry-version }}-

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: poetry install ${{ inputs.install-args }}
