---
- name: Deploy monitoring stack
  hosts: webservers
  become: true
  vars_files:
    - ../group_vars/all.yml

  tasks:
    - name: Run monitoring role
      ansible.builtin.include_role:
        name: monitoring
        apply:
          tags:
            - monitoring
      tags:
        - monitoring
        - monitoring_deploy
        - compose
