---
- name: Provision web servers
  hosts: webservers
  become: true

  tasks:
    - name: Run common role tasks/defaults
      ansible.builtin.include_role:
        name: common
        tasks_from: common_tasks
        defaults_from: common_defaults
        apply:
          tags:
            - common
      tags:
        - common
        - packages
        - users

    - name: Run docker role tasks/defaults/handlers
      ansible.builtin.include_role:
        name: docker
        defaults_from: docker_defaults
        apply:
          tags:
            - docker
      tags:
        - docker
        - docker_install
        - docker_config
