apiVersion: apps/v1
kind: Deployment
{{- $envVars := include "devops-app-py.envVars" . | trim }}
{{- $vaultAnnotations := include "devops-app-py.vaultAnnotations" . | trim }}
metadata:
  name: {{ include "devops-app-py.fullname" . }}
  labels:
    {{- include "devops-app-py.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.maxSurge }}
      maxUnavailable: {{ .Values.deployment.strategy.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "devops-app-py.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or $vaultAnnotations .Values.podAnnotations }}
      annotations:
        {{- if $vaultAnnotations }}
        {{- $vaultAnnotations | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "devops-app-py.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/part-of: {{ .Values.partOf }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "devops-app-py.serviceAccountName" . }}
      containers:
        - name: {{ include "devops-app-py.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if .Values.secrets.enabled }}
          envFrom:
            - secretRef:
                name: {{ include "devops-app-py.secretName" . }}
          {{- end }}
          {{- if $envVars }}
          env:
            {{- $envVars | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
