{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-app-py.secretName" . }}
  labels:
    {{- include "devops-app-py.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_USERNAME: {{ .Values.secrets.stringData.APP_USERNAME | quote }}
  APP_PASSWORD: {{ .Values.secrets.stringData.APP_PASSWORD | quote }}
{{- end }}
