{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devops-app-py.serviceAccountName" . }}
  labels:
    {{- include "devops-app-py.labels" . | nindent 4 }}
{{- end }}
